<?php

// Take domain GET request
$domain = $_GET['domain'] ?? $_POST['domain'] ?? null;

// Host of the current page
$host = $_SERVER['HTTP_HOST'];

// Load the functions
require_once 'functions.php';

if (isset($domain)) {
    // Get current timestamp
    $timestamp = time();
    $api_paste_name = $domain . '_' . $timestamp;

    // Send request to the API endpoint, follow redirects
    $api_json = api_v1($domain);
    $pastebin_url = pastebin($api_json, $api_paste_name);
} else {
    $api_json = null;
}

?>

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>WallMeter - GFW Blocking Detection</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- highlight.js -->
    <link type="text/css" href="assets/index.css" rel="stylesheet"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/ocean.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>

  </head>

  <header class="p-3 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="index.php" class="nav-link px-2 text-secondary">Home</a></li>
          </ul>

          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <!-- <input class="form-control form-control-dark" target="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" placeholder="Test a domain..." aria-label="Test"> -->
          </form>

          <div class="text-end">
            <a type="button" class="btn btn-outline-light me-2" href="/user/login.php" target="_blank">Login</a>
            <a type="button" class="btn btn-primary" href="/user/login.php#create" target="_blank">Sign-up</a>
          </div>
        </div>
      </div>
    </header>

  <body class="bg-light">

    

    <div class="container">
      <div class="py-5 text-center">
        
        <h2>WallMeter</h2>
        <p class="lead">Detect if your website is blocked in China by testing with servers at multiple locations</p>
        <p class="lead">从中国大陆多个地区的不同运营商检测你的网站是否被DNS污染或阻断</p>
      </div>

      <div class="row">
        
        <div class="col-md-12 order-md-1">
          <h4 class="mb-3">Test Now</h4>
          <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

            <?php if (!isset($domain)): ?>
            <div class="mb-3">
              <div class="col-md-12 mb-3">
                <label for="firstName">Domain name</label>
                <input type="text" class="form-control" id="domain" name="domain" placeholder="example.com" value="google.com" required>
                <div class="invalid-feedback">
                  Valid domain name is required.
                </div>
              </div>
            </div>
            <?php endif; ?>

            <?php if (isset($domain)): ?>

            <div class="mb-3">
              <label for="username">Sharable Result URL</label>
                <div class="alert alert-success" role="alert">
                    <a href="<?php echo $pastebin_url; ?>"><?php echo $pastebin_url; ?></a>
                </div>
            </div>

            <div class="mb-3">
              <label for="username">Result in JSON format</label>
                <pre><code>
                </code></pre>
                <script>
                    // Generated by CoffeeScript 2.0.1
                    (function() {
                    var data, init;
                    data = void 0;
                    init = async function() {
                        data = <?php echo $api_json; ?>;
                        // Set code text as the loaded prettified JSON
                        document.querySelector('code').innerHTML = JSON.stringify(data, null, "  ");
                        // Highlights the JSON
                        return hljs.highlightBlock(document.querySelector('code'));
                    };
                    init();
                    }).call(this);
                </script>

            </div>

            <?php endif; ?>

            <?php if (!isset($domain)): ?>
            <button class="btn btn-primary btn-lg btn-block" type="submit" id="submitButton" data-loading-text="Testing ...">Perform Testing</button>
            <script>
              $('#submitButton').on('click', function () {
                var $btn = $(this).button('loading')
                // business logic...
                $btn.button('reset')
              })
            </script>
            <?php endif; ?>

          </form>
        </div>
      </div>

    <!-- Divider -->
    <hr class="mb-4">

    <?php if (!isset($domain)): ?>
    <div class="row">
        <div class="col-md-12 order-md-1">
            <h5 class="mb-3">API v1 Endpoint</h4>
            /v1/api.php?domain=google.com
        </div>
    </div>

    <!-- Divider -->
    <hr class="mb-4">

    <div class="row">
        <div class="col-md-12 order-md-1">
            <h5 class="mb-3">API v1 Response Example</h4>
            <pre><code></code></pre>
            <script>
                // Generated by CoffeeScript 2.0.1
                (function() {
                var data, init;
                data = void 0;
                init = async function() {
                    // Data loading
                    data || (data = (await fetch('assets/example_response.json').then(function(response) {
                    return response.json();
                    })));
                    // Set code text as the loaded prettified JSON
                    document.querySelector('code').innerHTML = JSON.stringify(data, null, "  ");
                    // Highlights the JSON
                    return hljs.highlightBlock(document.querySelector('code'));
                };
                init();
                }).call(this);
            </script>
        </div>
    </div>
    <!-- Divider -->
    <hr class="mb-4">

    <?php endif; ?>

    <div class="row">
        <div class="col-md-12 order-md-1">
            <h5 class="mb-3">API v1 Response Fields</h4>
            Per node:
              <ul>
              <li><code>blocked</code> - whether the service is blocked from a node</li>
              <li><code>as_detected_cn</code> - AS number detected by the node in China</li>
              <li><code>as_detected_us</code> - AS number detected by the node in the US</li>
              <li><code>ip_detected_cn</code> - IP detected by the node in China</li>
              <li><code>ip_detected_us</code> - IP detected by the node in the US</li>
              <li><code>web_server_status_cn</code> - Port check on 80 and 443 performed by the node in China</li>
              <li><code>web_server_status_us</code> - Port check on 80 and 443 performed by the node in the US</li>
              </ul>
            Overall:
              <ul>
              <li><code>percentage_blocking_score</code> - A percentage score ranged from 0 to 1 representing how likely is the service blocked (1 = most likely)</li>
              <li><code>evaluation</code> - a text description of the testing result</li>
              </ul>

        </div>
    </div>

    <!-- Divider -->
    <hr class="mb-4">

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; O3O.CA</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="https://home.o3o.ca/" target="_blank">Home</a></li>
        </ul>
      </footer>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  </body>
</html>
